# Generated by Django 5.2 on 2025-04-29 11:46

import django.core.validators
import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ads", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="text",
            field=tinymce.models.HTMLField(
                validators=[
                    django.core.validators.MinLengthValidator(
                        3, "Comment must be greater than 3 characters"
                    )
                ]
            ),
        ),
    ]
