# Generated by Django 4.2.7 on 2025-04-16 15:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("ads", "0006_ad_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="ad",
            name="responsible",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="responsible",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
